services:
  back-end:
    container_name: Back-End
    build: ./Back-End
    volumes:
      - ./Back-End:/var/www/html
    ports:
      - 5000:80

  front-end:
    build: ./Front-End
    ports:
      - "5173:5173"
    volumes:
      - ./Front-End:/usr/src/app
      - /usr/src/app/node_modules